<!DOCTYPE html>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <title><?php echo SITE_NAME; ?></title>
	    
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />

        <?php
            echo $this->partial(
                'partials/header/dependencies.phtml'
            );
        ?>
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->			
		
        <?php
            global $layoutType;
			echo $this->partial(
				'partials/header/navbar.phtml', 
				array(
    				'type' => $layoutType
				)
			); 
		?>
		
	    <div class="container<?php echo $layoutType; ?>">
            <div class="row">
				<!-- Left column -->
                
                <div class="col-lg-12">

                    <div class="page-header">
                        <div class="text-right">
                            <span>
                                <?php echo translate('duration'); ?>:  <?php echo $this->total['duration_text']; ?>
                            </span>

                                &nbsp;/&nbsp;

                                <span>
                                <?php echo $this->total['count']; ?> <?php echo translate('songs'); ?>
                            </span>
                        </div>
                    </div>

                    <ul id="playlistActual" class="list-group"></ul>

                    <!-- START:     No Messages Notice -->
                    <div id="noticeNoMessages" class="text-center alert alert-info">
                        <i class="fa fa-exclamation-triangle"></i> <?php echo translate('no_tracks'); ?>
                    </div>                    
                    <!-- END:       No Messages Notice -->

                    <div class="tab-content tab-filter">
                        <div id="mostRecent" class="tab-pane active">
                            <ul class="list-group" id="statusList"></ul>
                        </div>
                    </div>
                    
					<div id="indicator-loading" class="indicator-custom text-center">
                        <?php echo translate('loading'); ?> <i class="fa fa-spinner fa-pulse"></i>
                	</div>
                
					<div id="indicator-finished" class="indicator-custom text-center">
						<i class="fa fa-check"></i> <?php echo translate('all_items_loaded'); ?>
					</div>                                                                                   
                </div>
                                            
            </div>
        </div>
   	    
		<script type="text/javascript">
		    $(document).ready(function() {

		    	// scrollUp
		        $.scrollUp({
		            scrollName: 'scrollUp',      // Element ID
		            scrollDistance: 300,         // Distance from top/bottom before showing element (px)
		            scrollFrom: 'top',           // 'top' or 'bottom'
		            scrollSpeed: 300,            // Speed back to top (ms)
		            easingType: 'linear',        // Scroll to top easing (see http://easings.net/)
		            animation: 'fade',           // Fade, slide, none
		            animationSpeed: 200,         // Animation speed (ms)
		            scrollTrigger: false,        // Set a custom triggering element. Can be an HTML string or jQuery object
		            scrollTarget: false,         // Set a custom target element for scrolling to. Can be element or number
		            scrollText: 'Scroll to top', // Text for element, can contain HTML
		            scrollTitle: false,          // Set a custom <a> title if required.
		            scrollImg: true,            // Set true to use image
		            activeOverlay: false,        // Set CSS color to display scrollUp active point, e.g '#00FFFF'
		            zIndex: 2147483647           // Z-Index for the overlay                    
		        });
		        
				// image preloading    							    		    		   			     			   
				$.imgpreload([
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});						
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});	
																			    
		    });			    		    				    
		</script>
		
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
		
		<!-- Bootbox -->							
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>		    
	</body>	
</html>
