	    <script id="templateStatus" type="text/x-jsrender">
	        <li id="playlistContainer-{{:id}}" class="list-group-item">
	            <a href="<?php echo PROTOCOL_RELATIVE_URL;?>/playlist/{{:id}}" class="">{{:name}}</a>
	        </li>
        </script>
        
        <script id="templateNotifyHtml" type="text/x-jsrender">
            <i id="notifyHtml-{{:id}}" class="fa fa-spinner fa-pulse"></i>
        </script>	