<!DOCTYPE html>
<html>
	<head>
	    <meta charset="UTF-8" />	
	    <title><?php echo SITE_NAME; ?> &mdash; <?php echo translate('error'); ?></title>
	    
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />

        <?php
            echo $this->partial(
                'partials/header/dependencies.phtml'
            );
        ?>
	    
	    <?php echo SITE_GLOBAL_HTML_HEADER; ?>									     
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>

	    <?php echo SITE_GLOBAL_HTML_BODY_START; ?>		
		
        <?php echo $this->partial('partials/header/navbar.phtml'); ?>
		
	    <div class="container-fluid">		      	
	      	<div>
		        <div class="row">
		          <div class="col-lg-12">
		            <div class="page-header">
		              <h1 id="type"><?php echo translate('error', 'strtoupper'); ?></h1>
		            </div>
		          </div>
		        </div>
		
		        <!-- Headings -->
		
		        <div class="row">
					<div class="col-md-12">
					    <div class="alert alert-danger">
							<i class="fa fa-exclamation-triangle"></i> <?php echo $this->message ?>
									
							<?php if( strlen( $this->trace ) ): ?>
								<div style="margin-bottom: 5px;"><i class="fa fa-bug"></i> <?php echo translate('exception'); ?>:</div>
								<div>	
									<textarea rows="50" cols="100" style="width: 100%;"><?php echo $this->trace ?></textarea>
								</div>		
							<?php endif; ?>
						</div>
					</div>
		        </div>
	      	</div>	      	
	    </div>
	    <!-- END:	Main Container -->
	    
	    
		<div class="footer">
			<div class="container-fluid">
		    	<div class="row">
		        	<div class="col-lg-12">		
		            	<ul class="list-unstyled">
		              		<li>
		              			<i class="fa fa-rss-square"></i>&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/rss">RSS</a>
		              		</li>
		            	</ul>
		            	<p>&copy; <?php echo translate('copyright'); ?> <?php echo date('Y'); ?> <?php echo SITE_NAME; ?>. <?php echo translate('all_rights_reserved'); ?>.</p>		
		          	</div>
		        </div>
      		</div>
    	</div>
    	    
		<script type="text/javascript">
		    $(document).ready(function() {	
		    			    				    							    		    		   			     			   
				$.imgpreload([
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});							
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});																    
		    });			    		    				    
		</script>

		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>			
		
		<!-- Bootbox -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>		    
		<?php echo SITE_GLOBAL_HTML_BODY_END; ?>
		
	</body>	
</html>
