<!DOCTYPE html>
<html>
	<head>
        <meta charset="UTF-8" />
	    <title><?php echo translate('login'); ?> &mdash; <?php echo SITE_NAME; ?></title>
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />

        <?php
            echo $this->partial(
                'partials/header/dependencies.phtml'
            );
        ?>

		<script type="text/javascript">
			var SOCIAL_LOGIN = null;
		</script>     

	    <?php echo SITE_GLOBAL_HTML_HEADER; ?>								     
	</head>

	<body style="padding-top: 0;">
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->
		
		<?php echo SITE_GLOBAL_HTML_BODY_START; ?>
		
		<div id="fb-root"></div>			
		
        <?php echo $this->partial('partials/header/navbar.phtml'); ?>
		
	    <div class="container-fluid" style="margin-top: 50px;">
	
	        <!-- Headings -->
	
	        <div class="row">
				<div class="col-lg-12">
					<div class="page-header">
						<h1>
							<?php echo translate('login'); ?>
						</h1>
					</div>

					<div id="frmErrors"></div>

					<div class="tab-content">
						<div class="tab-pane active" id="tabLocal">
							<div style="margin-top: 20px;">
								<form class="" action="" method="POST" name="frmUserLogin" id="frmUserLogin">
									<div class="form-group">
										<input autocomplete="off" type="text" class="form-control input-lg" placeholder="<?php echo translate('email'); ?>" id="frmEmail" name="email" data-required="1" data-type="email">
									</div>

                                    <div class="form-group">
                                        <input autocomplete="off" type="password" class="form-control input-lg" placeholder="<?php echo translate('password'); ?>" id="frmPassword" name="password" data-required="1" data-type="text">
                                    </div>

									<div class="form-group">
										<button id="btnUserLogin" class="btn btn-primary btn-lg btn-block"><?php echo translate('login'); ?></button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
		
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>
		<script type="text/javascript">
		    $(document).ready(function() {

				$('#btnUserLogin').click(function(event) {
					event.preventDefault();

					if( !formIsValid('frmUserLogin') ) {
						$('#frmUserLogin').effect('shake');
						return false;
					}					
						
					$.blockUI({
						message: '<i class="fa fa-spinner fa-spin"></i>'
					});

					<?php if( SITE_LOGIN_TYPE == 'email' ): ?>
					
                        $.ajax({
                            type: 'POST',
                            url: BASEURL + '/users/ajax',
                            data: {
                                method: 'userLogin',
                                username: $('#frmEmail').val()
                            },
                            complete: function( jqXHR, textStatus ) {
                                // ...
                            },
                            success: function( response, textStatus, jqXHRresponse ) {
                                if( response.status == 'OK' ) {
                                    if( response.result == 'MUST_VERIFY' ) {
                                        $('#frmErrors').html('');
                                        $('#btnUserLogin').remove();

                                        // success message
                                        var message = '<i class="fa fa-check"></i> ' + str_replace( '%EMAIL%', $('#frmEmail').val(), translate('check_email_verify_login') );

                                        // display the success message
                                        $('#frmUserLogin').html('<div class="alert alert-success">'+ message +'</div>');

                                        // unblock the interface
                                        $.unblockUI();
                                    } else {
                                        // error
                                    }
                                } else {
                                    $('#frmErrors').html('<div class="alert alert-danger"><i class="fa fa-warning"></i> '+ translate('authentication_failure') +'</div>')
                                    $.unblockUI();
                                }
                            },
                            error: function( jqXHR, textStatus, errorThrown ) {
                                $.unblockUI();
                            },
                            dataType: 'json'
                        });

                <?php else: ?>
                    $.ajax({
                        type: 'POST',
                        url: BASEURL + '/users/ajax',
                        data: {
                            method: 'userLogin',
                            username: $('#frmEmail').val(),
                            password: sha1( $('#frmPassword').val() )
                        },
                        complete: function( jqXHR, textStatus ) {
                            // ...
                        },
                        success: function( response, textStatus, jqXHRresponse ) {
                            if( response.status == 'LOGIN_OK' ) {
                                window.location.reload();
                            } else {
                                $('#frmErrors').html('<div class="alert alert-danger"><i class="fa fa-warning"></i> '+ translate('authentication_failure') +'</div>')
                                $.unblockUI();
                            }
                        },
                        error: function( jqXHR, textStatus, errorThrown ) {
                            $.unblockUI();
                        },
                        dataType: 'json'
                    });
                <?php endif; ?>
				});
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});																    
		    });
		</script>	
		
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>		

		<!-- Bootbox.js -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.js"></script>

        <!-- Form Validation -->
        <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.validation.js"></script>

        <?php echo SITE_GLOBAL_HTML_BODY_END; ?>
	</body>	
</html>
