<div class="col-lg-2" style="padding-bottom: 10px;">
    <div style="position: relative;">
        <div>
            <img class="avatar-sm img-responsive" src="<?php echo $_SESSION['user']['avatar_url']; ?>">
        </div>

        <div style="position: absolute; top: 0; left: 42px;">
            <div style="font-size: small;">
                <?php echo $_SESSION['user']['first_name']; ?> <?php echo $_SESSION['user']['last_name']; ?>
            </div>

            <div style="font-size: x-small;">
                <?php echo $_SESSION['user']['email']; ?>
            </div>
        </div>
    </div>
</div>