<!DOCTYPE HTML>
<HTML>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>__SITE_NAME__ - ERROR</title>
	<link href="__THEME_PATH__/bootstrap.min.css" rel="stylesheet">

	<script type="text/javascript">
		var BASEURL					= '__PROTOCOL_RELATIVE_URL__';
		var DEFAULT_PRELOADER_IMAGE = '__SITE_DEFAULT_PRELOADER_IMAGE_PATH__';
	</script>

	<script type="text/javascript" src="__JS_PATH__/jquery-1.9.1.min.js"></script>
	<script type="text/javascript" src="__JS_PATH__/jquery.blockUI.js"></script>
	<script type="text/javascript" src="__JS_PATH__/jquery.blockUI.defaults.js"></script>
	<script type="text/javascript" src="__JS_PATH__/bootstrap/bootstrap.min.js"></script>
	<script type="text/javascript" src="__JS_PATH__/bootstrap/extensions/bootbox/bootbox.js"></script>
	<script type="text/javascript">
		$(function() {
			bootbox.dialog({
				closeButton: false,
				title: '__SITE_NAME__',
				message: '__ERROR_MESSAGE__',
				buttons: {
				}
			});
		});
	</script>

	<style type="text/css">
		body{
			font: "Trebuchet MS", sans-serif;
			margin: 50px;
		}
	</style>
</head>
<body></body>
</HTML>